{"componentChunkName":"component---src-templates-blog-template-tsx","path":"/blog/d0c23b16c8178eba8ec4/","result":{"data":{"markdownRemark":{"html":"<p>ターミナルで使えるメモプログラム<a href=\"http://maebert.github.io/jrnl/index.html\" rel=\"nofollow noopener\" target=\"_blank\">jrnl</a>はスーパー便利なのですが、ふとした拍子におかしくなった。</p>\n<p>何叩いてもこのエラーが</p>\n<div class=\"code-frame\" data-lang=\"text\"><div class=\"highlight\"><pre>$ jrnl\nTraceback (most recent call last):\n  File \"/usr/local/bin/jrnl\", line 9, in &lt;module&gt;\n    load_entry_point('jrnl==1.8.1', 'console_scripts', 'jrnl')()\n  File \"/Library/Python/2.7/site-packages/jrnl/cli.py\", line 159, in run\n    touch_journal(config['journal'])\n  File \"/Library/Python/2.7/site-packages/jrnl/cli.py\", line 92, in touch_journal\n    util.prompt(\"[Journal created at {0}]\".format(filename))\nUnicodeEncodeError: 'ascii' codec can't encode characters in position 0-12: ordinal not in range(128)\n</pre></div></div>\n<p>対象ソース読んでみるとファイル開くときに落ちてるくさい。</p>\n<p><code>$ jrnl -ls</code>は通るからどっかにunicode混じってるのかなと思って~/.jrnl_configをのぞくと案の定unicodeが混じってた。</p>\n<div class=\"code-frame\" data-lang=\"jrnl_config\"><div class=\"highlight\"><pre>{\n  \"default_hour\": 9, \n  \"timeformat\": \"%Y-%m-%d %H:%M\", \n  \"linewrap\": 79, \n  \"encrypt\": false, \n  \"editor\": \"\", \n  \"default_minute\": 0, \n  \"highlight\": true, \n  \"journals\": {\n    \"default\": \"\\u307b\\u3052\\u307b\\u3052\\u307b\\u3052\\u307b\\u3052\\u307b\\u3052\\u307b\\u3052\"\n  }, \n  \"tagsymbols\": \"@\"\n}\n</pre></div></div>\n<p>対象部分をさっと<code>\"~/jrnl.txt\"</code>にかえたら治った。</p>\n<p>なんでこういうことになったのかよくわかってないです汗</p>","frontmatter":{"date":"2014-06-26","slug":"/blog/d0c23b16c8178eba8ec4","title":"Mac/Marvericksのjrnl(Python)でUnicodeEncodeErrorが出て困った。","image":null,"tags":["Python","Mac","jrnl"]}}},"pageContext":{"slug":"/blog/d0c23b16c8178eba8ec4"}},"staticQueryHashes":["1342192543"]}